name: Shell Commands

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello world"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: check npm version
        run: npm -v
      - name: python command
        run: |
         import platform
         print(platform.processor())
        shell: python
